//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppECart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int orderDetailId { get; set; }
        public int orderId { get; set; }
        public string itemId { get; set; }
        public decimal quantity { get; set; }
        public decimal unitPrice { get; set; }
        public decimal total { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
